# Sample configuration file for gRPC Load Test Client
# Copy this file and modify according to your needs

target:
  host: "localhost"
  port: 8080
  method: "Echo"  # Options: Echo, ComputeHash, HealthCheck
  use_tls: false
  tls_cert_path: null  # Path to TLS certificate if needed
  request_template:
    message: "Load test message"
    metadata:
      "test-id": "load-test-001"
      "client-version": "1.0.0"

load:
  tps: 100                          # Target transactions per second
  duration: "PT1M"                  # Test duration (ISO-8601: PT1M = 1 minute)
  warmup_duration: "PT10S"          # Warmup duration (PT10S = 10 seconds)
  ramp_up_duration: "PT0S"          # Ramp-up duration (PT0S = no ramp-up)
  max_concurrent_requests: 1000     # Maximum concurrent requests

client:
  max_concurrent_requests: 1000     # Maximum concurrent requests
  request_timeout_ms: 5000          # Request timeout in milliseconds
  keep_alive_time_ms: 30000         # Keep-alive time
  keep_alive_timeout_ms: 5000       # Keep-alive timeout
  keep_alive_without_calls: true    # Keep-alive without active calls
  max_inbound_message_size: 4194304 # 4MB maximum message size
  user_agent: "grpc-load-test-client/1.0"

reporting:
  reporting_interval_seconds: 10    # Real-time reporting interval
  enable_real_time_stats: true      # Enable real-time statistics
  output_format: "console"          # Options: console, json, csv
  output_file: null                 # Output file path (optional)
  percentiles: [0.1, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99]  # Percentiles to calculate